### ISSUE TITLE
Add Goggle SIgnIn/Login

### ISSUE THREAD

**Issue by ritankarsaha** [Dev-tanay/Rubik-Cube#104]
I intend to add the goggle login/ signin option to this page so that the users can have their own personalised profile. The goggle login button will be added befoe this page loads into action.

<img width="1512" alt="Screenshot 2024-05-16 at 2 13 01 AM" src="https://github.com/Dev-tanay/Rubik-Cube/assets/136831315/54bc62dd-d7a8-4781-82c7-d237ddc26d58">

**Comment by ritankarsaha** [comment]
Please also add the labels gssoc and level under this issue.

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.

**Comment by ritankarsaha** [comment]
I have opened the pull request #121 for this issue. 
Thank You
