### ISSUE TITLE
Back option on leaderboad page

### ISSUE THREAD

**Issue by kanishka-parmar** [Dev-tanay/Rubik-Cube#112]
![Screenshot 2024-05-16 234952](https://github.com/Dev-tanay/Rubik-Cube/assets/114792553/aad58af8-33ba-4c30-b6f3-530c4dae4813)

as I clicked on this trophy button, this page opened.

![Screenshot 2024-05-16 235055](https://github.com/Dev-tanay/Rubik-Cube/assets/114792553/3538d636-b7b7-42db-b1d2-7e6904b62ef9)

Now if I want to go to the home page to play the game I need to refresh the page then I can go but it's not good for users so I suggest a back button or navigation bar to easily navigate throughout the site.

I want to contribute it under GSSOC'24. Please assign me.

**Comment by kanishka-parmar** [comment]
Thanks for assigning! 
I should just put the back button or should design navigation bar where we can find each details?

**Comment by rajkrsingh9** [comment]
Please assign me this issue, if still its not solved. I would work over adding a better and comforting navigation bar because as a game website the currently used theme is very dull. The navbar will have : 
Home button- visit the game arena
leaderboard - 
settings - 
login/signup page button- (if required)

**Comment by unnatinarayan** [comment]
I am a web developer and a first time open source contributor. Please assign me this issue. I will create a navbar for you which will work for all pages. It would also be responsive . I want to contribute under GSSOC'2024

**Comment by Suvendu-UI** [comment]
i also want to contribute to this issue so pls assign me

**Comment by satyaveni299** [comment]
I  will work on this back button issue ,plz assign me this under SSOC'24
