### ISSUE TITLE
Adding a README file

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [Dev-tanay/Rubik-Cube#122]
I've noticed your project lacks a README.md file, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

Thank you @Dev-tanay

**Comment by Dev-tanay** [comment]
Already Done

**Comment by iamkanhaiyakumar** [comment]
But in this missing installation guidelines some beginner contributor don't understand how to pull or push the repo this cause I raised this issue. 
Thank you @Dev-tanay
