### ISSUE TITLE
Adding an Issue Template

### ISSUE THREAD

**Issue by Sambit-Mondal** [Dev-tanay/Rubik-Cube#127]
- We all know presentation is important for everything we do.
- An issue, raised for contributing to the project, is not an exception.
- An Issue Template would make things simpler for the Project Admin to understand.
- It would also streamline the process of highlighting the main points.

<strong>Implementation:</strong>
- The Issue template would be subdivided into two sections: One entitled "New Feature Request" and the other would be entitled "Bug Report".
- Both the subdivisons will have different templates.

<strong>New Feature Request:</strong>
- Describe the issue you want to solve through this feature.
- Mention the feature you want to add.
- Mention the program for which you want to contribute.
- Checkbox to agree with the Contributing guidelines.

<strong>Bug Report:</strong>
- Give a brief about the bug
- What is the expected behaviour
- Description on how you will solve the bug
- Mention the program for which you want to contribute.
- Checkbox to agree with the Contributing guidelines.

@Dev-tanay Kindly assign me this issue under GSSoC '24.
Thank you!

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
