### ISSUE TITLE
Creating a logo for the website

### ISSUE THREAD

**Issue by samridhi171** [Dev-tanay/Rubik-Cube#159]
Adding a logo can be a nice idea. I have experience with logo designing assign it to me under Gssos'24. @Dev-tanay

**Comment by raunakcy** [comment]
Can you please assign me this task?
@Dev-tanay

**Comment by raunakcy** [comment]
ok

**Comment by meenakshiiyer2531** [comment]
Hey @Dev-tanay 
Can this issue be assigned to me for gssoc 24. I would complete it up on time.
Regards,
V Meenakshi Iyer

**Comment by meenakshiiyer2531** [comment]
Hey @Dev-tanay 
I had made two samples of the logo, please let me know how can I share those designs. 
Regards,
 V Meenakshi Iyer
