### ISSUE TITLE
Doumentation Fix

### ISSUE THREAD

**Issue by nimitagarwal26** [Dev-tanay/Rubik-Cube#172]
Hii @Dev-tanay 
The documentation does not contain the technology used section. A good documentation must contain what all techs are being used in the project. 
I would love to fix this documentation issue. Please assign it to me under GSSoC'24.

**Comment by nimitagarwal26** [comment]
Can you please level this issue?

**Comment by nidhirajpoot** [comment]
please assign me this documentation i also want to contribute @nimitagarwal26

**Comment by nimitagarwal26** [comment]
Hii @Dev-tanay 
Could you please assign level to this issue because I won't be scored if level is not assigned.

**Comment by meenakshiiyer2531** [comment]
hello @Dev-tanay 
Can you please assign me the issue for gssoc '24. 
Regards,
V Meenakshi Iyer
