### ISSUE TITLE
Adding Try Again Option

### ISSUE THREAD

**Issue by Aaryan-Ajith-Dev** [Dev-tanay/Rubik-Cube#201]
Problem Statement: Once the user has completed the challenge, there is no way for the user (other than refreshing the website) to get to the main menu (or any other page).

Solution Proposed: Add a 'try again' option redirecting the user to the main menu.

Expected behavior: The user will get redirected to the main menu once he clicks the button.

<img width="959" alt="Screenshot 2024-05-31 191225" src="https://github.com/Dev-tanay/Rubik-Cube/assets/117074091/dcece670-e612-42c3-8561-2a250b774ab1">

I agree to follow this project's Code of Conduct.
I'm an SSoC'24 contributor.
I want to work on this issue, please assign it to me @Dev-tanay.

**Comment by dvnshi** [comment]
Please assign me this issue under gssoc24

**Comment by pranjalg1331** [comment]
@Dev-tanay are you still working on this issue?
I would like to try too.
