### ISSUE TITLE
Add Leaderboard

### ISSUE THREAD

**Issue by vverma022** [Dev-tanay/Rubik-Cube#202]
**Add a leaderboard so that people can see and compete.**
How I would do this ? 

1. Add a name prompt that takes in the username of the player
2. add a leaderboard toggle to see the leaderboard 
3. once the cube is solved the result is stored and compared and shown

**Comment by vverma022** [comment]
I'd like to implement this feature and try implementing it

**Comment by Divyanshi1611** [comment]
I'm Divyanshi and I'd love to help with Rubik-cube. Can you please assign issue #202 to me to add the leaderboard feature?
