### ISSUE TITLE
Additon of Preloader

### ISSUE THREAD

**Issue by Anjaliavv51** [Dev-tanay/Rubik-Cube#211]
Assign under GSSOC
Addition of preloader which gives clarity to the user that the webpage is still loading.

**Comment by satyaveni299** [comment]
Can you please assign me this under SSOC'24,I can add pre loder

**Comment by Anjaliavv51** [comment]
@Dev-tanay  please review the PR

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the changes

**Comment by Anjaliavv51** [comment]
@Dev-tanay please add level 2 label as it contains both , addition of Preloader and contributors logo
