### ISSUE TITLE
Addition of Custom Cursor

### ISSUE THREAD

**Issue by Anjaliavv51** [Dev-tanay/Rubik-Cube#215]
![Screenshot 2024-06-01 172517](https://github.com/Dev-tanay/Rubik-Cube/assets/154777864/b4aa778e-63ae-404f-820c-1a8bbad58b76)

**Comment by VanshikaSabharwal** [comment]
Hey @Dev-tanay . I can add custom cursor .Can you please assign me this issue and add level to it.

**Comment by Sayantan-Karmakar** [comment]
Hi @Dev-tanay I am interested to work on this issue. Kindly please assign me this.

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the changes

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the PR
