### ISSUE TITLE
Updating of Icons Colour For Better Visual Experience to the User #SSOC

### ISSUE THREAD

**Issue by malathinani** [Dev-tanay/Rubik-Cube#226]
- The User Experience of the **Rubik's Cube** game is highly appreciable. However, for better **Visual Experience** the icons colour  need to be changes. 
- While playing the "Rubik's cube" game i find it difficult to identify the icons on the Webpage as they were in Light grey colour. 
- To identify the icons fastly and use it effectively, we need to change  the colour of the icon to people's comfortable colour.
- As per my research in Google, most of the users prefer Blue or Light Blue colour to use for Icons.
- Since it is my First Open Source Contribution, I'm very excited to contribute in your project .
- If you like the idea , please assign it to me so that i can give a better visual experience for the user.
#SSOC

**Comment by Dev-tanay** [comment]
already looks good, There is no need to change
