### ISSUE TITLE
Color Customisation for Rubik Cube

### ISSUE THREAD

**Issue by shreya-2410** [Dev-tanay/Rubik-Cube#237]
**Description**
Currently, the Rubik's Cube simulator does not allow users to customize the colors of the cube. Adding color customization functionality would enhance the user experience and allow users to personalize their cube according to their preferences.

Proposal
- Implement a UI element (e.g., dropdown menus, color pickers) to allow users to select colors for each face of the Rubik's Cube.
- Write JavaScript functions to handle the color customization logic and update the cube's colors accordingly.
- Modify the code responsible for rendering the Rubik's Cube to use the custom colors defined by the user.

Additional Details
- This feature would be valuable for users who want to customize the appearance of the Rubik's Cube to their liking.
- It aligns with our goal of providing a flexible and user-friendly Rubik's Cube simulator.
pls assign this task to me @Dev-tanay for ssoc

**Comment by Dev-tanay** [comment]
There is already a color customization feature
