### ISSUE TITLE
Addition light mode and dark mode 

### ISSUE THREAD

**Issue by DiwareNamrata23** [Dev-tanay/Rubik-Cube#241]
By adding the day mode and night mode the user . It will help them to choose the mode of their convince which can helps to reduce eye strain in the long-term use of screens. Kindly assign this issue to me @Dev-tanay 
thank you!

**Comment by INam1995** [comment]
@Dev-tanay,
I would like to take on the task of implementing a light and night mode for our user interface. This feature will allow users to select their preferred mode, helping to reduce eye strain during prolonged screen use. Please assign this issue under SSOC'24.
Thanks!!
