### ISSUE TITLE
Add Keyboard Shortcuts for better gaming experience

### ISSUE THREAD

**Issue by Anushka-Pote** [Dev-tanay/Rubik-Cube#250]
Currently, the Rubik's Cube game can only be manipulated through mouse interactions, which might not be the most efficient or convenient method for all users. Adding keyboard shortcuts for twisting and solving the cube can enhance the gameplay experience, making it more accessible and faster for users to interact with the Rubik's Cube.

**Comment by ooye-sanket** [comment]
hello can you assign this issue to me can you assign this to me

**Comment by Anushka-Pote** [comment]
@ooye-sanket I am actually working on it currently and the functionality is in the wrapped up stage.
