### ISSUE TITLE
Adding new feature of user can chose multiple types of rubik-cube

### ISSUE THREAD

**Issue by Chelseasingla1** [Dev-tanay/Rubik-Cube#30]
I would like to add a feature where user can chose one rubik-cube of multiple types like different colors and different sizes.
Please assign me this issue under GSSoC'24

**Comment by prajna321** [comment]
@Dev-tanay,
I'm experienced in HTML, CSS, Tailwind CSS, JavaScript, and React.js, with ongoing work on a MERN project. I'm keen to contribute by implementing a feature allowing users to customize Rubik's cubes with color and layer options. 
Check out my background and projects on LinkedIn: https://www.linkedin.com/in/prajna-paul-117086256/ and GitHub: https://github.com/prajna321/ Please assign relevant tasks; I'm committed to effective contributions.
Thank you!
