### ISSUE TITLE
[Feature] Add Email and Additional Profile Info Fields

### ISSUE THREAD

**Issue by Swapnilden** [Dev-tanay/Rubik-Cube#346]
### Description

Currently, the profile update functionality includes only the user's name and profile picture. To provide a more comprehensive user profile, additional fields for email and additional profile information should be added. This will allow users to provide more details about themselves and improve personalization.

### Screenshots

![Screenshot (84)](https://github.com/Dev-tanay/Rubik-Cube/assets/142904704/e0a349e6-0741-4953-bc29-b52e742661b6)

### Proposed Solution (optional)

1. HTML Form Update:

- Add input fields for email and additional profile information in the profile update form.

2. JavaScript Update:

- Update the validation logic to ensure that all fields (name, email, additional info, and profile picture) are filled before submission.
- Store the updated profile information, including the new fields, in localStorage.
- Load and display the additional profile information when the user signs in.

3. LocalStorage:

- Ensure the additional fields are stored persistently in localStorage.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Dev-tanay/Rubik-Cube/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Swapnilden** [comment]
Please assign me this issue under GSSOC'24

**Comment by ishikajain1234** [comment]
I would like to work on this project .plz assign me
