### ISSUE TITLE
Add About Page with Rubik's Cube Solution Formulas

### ISSUE THREAD

**Issue by Manav173** [Dev-tanay/Rubik-Cube#41]
Currently, the project lacks an "About" page, which could serve as a valuable resource for users interested in learning about Rubik's Cube solving methods. This issue proposes the addition of an "About" page that provides basic information about Rubik's Cubes and includes a comprehensive list of formulas and algorithms for solving the Rubik's Cube.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @Dev-tanay  .

**Comment by Sneha4580** [comment]
Empower your project with an engaging 'About' page featuring the Rubik's cube formula. 
Please give a chance to work on this project @Dev-tanay .

**Comment by Dev-tanay** [comment]
assigned.
do star the repo.

**Comment by Dev-tanay** [comment]
> Currently, the project lacks an "About" page, which could serve as a valuable resource for users interested in learning about Rubik's Cube solving methods. This issue proposes the addition of an "About" page that provides basic information about Rubik's Cubes and includes a comprehensive list of formulas and algorithms for solving the Rubik's Cube.
> 
> I would be really thankful if you assign me this issue as a part of GSSoC'24 @Dev-tanay .

assigned.
do star the repo.

**Comment by Dev-tanay** [comment]
> is proj

assigned.
do star the repo.

**Comment by anupa-rb** [comment]
Hi there, I've been learning UI/UX and I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by abhinavraajput** [comment]
@Dev-tanay Please assign this issue under GSSOC'24 , i will fix this issue.

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.

**Comment by rajkrsingh9** [comment]
Please assign me this issue! I would work in providing a about page that is both responsive and matches the theme of a game webpage. I would be fulfilling the requirements as a contributor of GSSOC'24.

**Comment by meenakshiiyer2531** [comment]
Hey @Dev-tanay 
Can this issue be assigned to me for gssoc 24. I would complete it up on time.
Regards,
V Meenakshi Iyer
