### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ShreeluSantosh** [Dev-tanay/Rubik-Cube#64]
I've gone through the project's repository, and while the website itself is simple and elegant, I noticed that the repository is missing its README.md.

Here is how Rubik-Cube's README.md will look like:

<hr>

<h1>Rubik-Cube</h1>

_[Link to game demo - https://dev-tanay.github.io/Rubik-Cube/]_

_[Screenshot of the game home screen]_
<img src="https://github.com/Dev-tanay/Rubik-Cube/assets/94289402/2c1cb7ab-7a9c-4d6e-a692-4e466d4bee5a" height="300">

**1. About the Game**

This section will talk briefly about Rubik Cube, and its objective.

**2. How to Play**

It will explain how to:
a. Rotate the segments of the cube
b. Change the view of the cube

Using the mouse cursor, as well as touch.

Explanatory screenshots will also be added.

**3. Installation**

Steps to clone the repository to local machine, and open the index.html file in any web browser, along with commands

**4. Navigating through the game screen**

This final section will explain various buttons on the screen, like leaderboard, stats, preferences, theme, reset.

**License**

This project is licensed under the MIT License - see the LICENSE file for details.

<hr>

I can develop this easy-to-read README.md for this project repository, if it's assigned to me under #gssoc label

**Comment by Dev-tanay** [comment]
Give it a star 

> I've gone through the project's repository, and while the website itself is simple and elegant, I noticed that the repository is missing its README.md.
> 
> Here is how Rubik-Cube's README.md will look like:
> 
> # Rubik-Cube
> _[Link to game demo - https://dev-tanay.github.io/Rubik-Cube/]_
> 
> _[Screenshot of the game home screen]_ <img alt="" height="300" src="https://private-user-images.githubusercontent.com/94289402/329836620-2c1cb7ab-7a9c-4d6e-a692-4e466d4bee5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTc2NDMsIm5iZiI6MTcxNTUxNzM0MywicGF0aCI6Ii85NDI4OTQwMi8zMjk4MzY2MjAtMmMxY2I3YWItN2E5Yy00ZDZlLWE2OTItNGU0NjZkNGJlZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YzAzYzEyNzYyYjM4NTU4OWY5OWUwMWRkNDlhMzQwNzhjMDdlYTM3ZjJiNzZmODgyMjU2YTgyNzEwYWFhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FFZcLRKsGQ2_2elv9qurOfI3EVE-ECwjGYOD9UPsKjU">
> 
> **1. About the Game**
> 
> This section will talk briefly about Rubik Cube, and its objective.
> 
> **2. How to Play**
> 
> It will explain how to: a. Rotate the segments of the cube b. Change the view of the cube
> 
> Using the mouse cursor, as well as touch.
> 
> Explanatory screenshots will also be added.
> 
> **3. Installation**
> 
> Steps to clone the repository to local machine, and open the index.html file in any web browser, along with commands
> 
> **4. Navigating through the game screen**
> 
> This final section will explain various buttons on the screen, like leaderboard, stats, preferences, theme, reset.
> 
> **License**
> 
> This project is licensed under the MIT License - see the LICENSE file for details.
> 
> I can develop this easy-to-read README.md for this project repository, if it's assigned to me under #gssoc label

Give it a star

**Comment by Dev-tanay** [comment]
Give it a star @ShreeluSantosh

**Comment by ShreeluSantosh** [comment]
Starred the repo @Dev-tanay

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
