### ISSUE TITLE
Add issue template 

### ISSUE THREAD

**Issue by officeneerajsaini** [Dev-tanay/Rubik-Cube#89]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature.

We recommend creating a “Report Bug” and “Feature Request” issue template.
you can refer this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Some suggested prompts/questions you can add to a “Report Bug” template are:

Briefly describe the bug
What is the expected behavior?
Please provide step by step instructions on how to reproduce the bug
Some suggested prompts/questions you can add to a “Feature Request” issue template are:

Briefly describe your feature request
What problem is this feature trying to solve?
How do we know when the feature is complete?

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/issues/new/choose
Click on Get Started button and copy the template to yours.

**Comment by officeneerajsaini** [comment]
@Dev-tanay  , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by officeneerajsaini** [comment]
gssoc label !

**Comment by officeneerajsaini** [comment]
@Dev-tanay level tag too

**Comment by Ayushigitgithub** [comment]
@Dev-tanay can you please assign this issue to me also would definitely put my best

**Comment by moulisaaa** [comment]
Can you label the issue?

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.
